# SquareLine LVGL GENERATED FILE
# EDITOR VERSION: SquareLine Studio 1.2.1
# LVGL VERSION: 8.2.0
# PROJECT: audio_mixer

import os
import sys

base_path = os.path.dirname(__file__)
lib_path = os.path.abspath(os.path.join(base_path, '..', '..'))
sys.path.insert(0, lib_path)

import lvgl as lv
import time


lv.init()

disp = lv.sdl_window_create(480, 800)

group = lv.group_create()
lv.group_set_default(group)
mouse = lv.sdl_mouse_create()
keyboard = lv.sdl_keyboard_create()
lv.indev_set_group(keyboard, group)


import fs_driver

fs_drv = lv.fs_drv_t()
fs_driver.fs_register(fs_drv, 'S')


dispp = lv.disp_get_default()
theme = lv.theme_default_init(dispp, lv.palette_main(lv.PALETTE_BLUE), lv.palette_main(lv.PALETTE_RED), False, lv.font_default())
lv.disp_set_theme(dispp, theme)

font_mos_semibold_16 = lv.font_load("S:ui_font_mos_semibold_16.bin")
font_number = lv.font_load("S:ui_font_number.bin")


def get_image(img_file):
    dsc = lv.img_dsc_t()
    with open(img_file, 'rb') as f:
        data = f.read()

    dsc.data = data
    dsc.data_size = len(data)
    return dsc


ui_img_audio_wave_1_png = get_image('ui_img_audio_wave_1.png')
ui_img_btn_eq_inact_png = get_image('ui_img_btn_eq_inact.png')
ui_img_btn_eq_act_png = get_image('ui_img_btn_eq_act.png')
ui_img_pot_ver_line_png = get_image('ui_img_pot_ver_line.png')
ui_img_pot_ver_knob_png = get_image('ui_img_pot_ver_knob.png')
ui_img_btn_1_inact_png = get_image('ui_img_btn_1_inact.png')
ui_img_btn_1_act_png = get_image('ui_img_btn_1_act.png')
ui_img_btn_play_inact_png = get_image('ui_img_btn_play_inact.png')
ui_img_btn_play_act_png = get_image('ui_img_btn_play_act.png')
ui_img_indicator_ver_png = get_image('ui_img_indicator_ver.png')
ui_img_btn_knob_png = get_image('ui_img_btn_knob.png')
ui_img_pot_hor_line_tempo_png = get_image('ui_img_pot_hor_line_tempo.png')
ui_img_pot_hor_knob_png = get_image('ui_img_pot_hor_knob.png')
ui_img_pot_hor_line_png = get_image('ui_img_pot_hor_line.png')


def Fadeoff_Animation(TargetObject, delay):
    def fade_opa_cb(a, v):
        lv.obj_set_style_opa(TargetObject, v, 0)

    PropertyAnimation_0 = lv.anim_t()
    lv.anim_init(PropertyAnimation_0)
    lv.anim_set_path_cb(PropertyAnimation_0, lv.anim_path_linear)
    lv.anim_set_time(PropertyAnimation_0, 100)
    lv.anim_set_var(PropertyAnimation_0, TargetObject)
    lv.anim_set_custom_exec_cb(PropertyAnimation_0, fade_opa_cb)
    lv.anim_set_delay(PropertyAnimation_0, delay + 0)
    lv.anim_set_repeat_count(PropertyAnimation_0, 0)
    lv.anim_set_repeat_delay(PropertyAnimation_0, 0) #+ 100
    lv.anim_set_playback_delay(PropertyAnimation_0, 0)
    lv.anim_set_playback_time(PropertyAnimation_0, 0)
    lv.anim_set_early_apply(PropertyAnimation_0, True)
    lv.anim_set_values(PropertyAnimation_0, 255, 0)
    lv.anim_start(PropertyAnimation_0)


def Fadeon_Animation(TargetObject, delay):
    def fade_opa_cb(a, v):
        lv.obj_set_style_opa(TargetObject, v, 0)

    PropertyAnimation_0 = lv.anim_t()
    lv.anim_init(PropertyAnimation_0)
    lv.anim_set_path_cb(PropertyAnimation_0, lv.anim_path_linear)
    lv.anim_set_time(PropertyAnimation_0, 100)
    lv.anim_set_var(PropertyAnimation_0, TargetObject)
    lv.anim_set_custom_exec_cb(PropertyAnimation_0, fade_opa_cb)
    lv.anim_set_delay(PropertyAnimation_0, delay + 0)
    lv.anim_set_repeat_count(PropertyAnimation_0, 0)
    lv.anim_set_repeat_delay(PropertyAnimation_0, 0) #+ 100
    lv.anim_set_playback_delay(PropertyAnimation_0, 0)
    lv.anim_set_playback_time(PropertyAnimation_0, 0)
    lv.anim_set_early_apply(PropertyAnimation_0, True)
    lv.anim_set_values(PropertyAnimation_0, 0, 255)
    lv.anim_start(PropertyAnimation_0)


# COMPONENTS
def BTN_EQ_eventhandler(event_struct):
    obj = lv.event_get_target_obj(event_struct)

    if lv.obj_has_state(obj, lv.STATE_CHECKED):
        Fadeoff_Animation(ui_Slider_group_left, 0)
        Fadeoff_Animation(ui_Slider_group_right, 200)
        Fadeoff_Animation(ui_Indicator_group, 100)
        Fadeon_Animation(ui_EQ_group, 200)
        Fadeon_Animation(ui_Tempo_group, 300)
        lv.obj_clear_flag(ui_EQ_group, lv.OBJ_FLAG_HIDDEN)
        lv.obj_clear_flag(ui_Tempo_group, lv.OBJ_FLAG_HIDDEN)
    else:
        Fadeon_Animation(ui_Slider_group_left, 0)
        Fadeon_Animation(ui_Indicator_group, 100)
        Fadeon_Animation(ui_Slider_group_right, 200)
        Fadeoff_Animation(ui_Tempo_group, 100)
        Fadeoff_Animation(ui_EQ_group, 0)
        lv.obj_add_flag(ui_Tempo_group, lv.OBJ_FLAG_HIDDEN)
        lv.obj_add_flag(ui_EQ_group, lv.OBJ_FLAG_HIDDEN)


def Label_Cut_1_eventhandler(event_struct):
    lv.obj_add_flag(ui_Audio_Player, lv.OBJ_FLAG_HIDDEN)


def Label_Cut_3_eventhandler(event_struct):
    print('Label_Cut_3_eventhandler')
    lv.obj_add_flag(ui_Audio_Player, lv.OBJ_FLAG_HIDDEN)
    print('Label_Cut_3_eventhandler')



ui_Audio_Player = lv.obj_create(lv.scr_act())
lv.obj_clear_flag(ui_Audio_Player, lv.OBJ_FLAG_SCROLLABLE)

lv.obj_set_width(ui_Audio_Player, 480)
lv.obj_set_height(ui_Audio_Player, 800)


lv.obj_set_style_bg_color(ui_Audio_Player, lv.color_hex(0x2D2F36), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Audio_Player, 255, lv.PART_MAIN | lv.STATE_DEFAULT)

ui_Footer = lv.obj_create(ui_Audio_Player)
lv.obj_set_height(ui_Footer, 128)
lv.obj_set_width(ui_Footer, lv.pct(100))
lv.obj_set_align(ui_Footer,  lv.ALIGN_BOTTOM_MID)
lv.obj_set_style_bg_color(ui_Footer,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Footer, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Footer,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Footer,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Footer,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Footer,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Footer,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Footer,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Footer,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Slider_AB = lv.slider_create(ui_Footer)
lv.obj_set_width(ui_Slider_AB, 276)
lv.obj_set_height(ui_Slider_AB, 79)
lv.obj_set_align(ui_Slider_AB,  lv.ALIGN_CENTER)
lv.slider_set_mode(ui_Slider_AB, lv.SLIDER_MODE_SYMMETRICAL)

if -100 < 100: 
    lv.slider_set_range(ui_Slider_AB, -100, 100)
    
lv.slider_set_value(ui_Slider_AB, 80, lv.ANIM_OFF)  # need refresh: -100,100

if 'SYMMETRICAL' == 'RANGE':
    lv.slider_set_left_value(ui_Slider_AB, 0, lv.ANIM_OFF)


lv.obj_set_style_bg_color(ui_Slider_AB,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider_AB, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Slider_AB,  ui_img_pot_hor_line_png, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Slider_AB,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Slider_AB,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Slider_AB,  35, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Slider_AB,  35, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Slider_AB,  lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider_AB, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_color(ui_Slider_AB,  lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_opa(ui_Slider_AB, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_width(ui_Slider_AB,  50, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_spread(ui_Slider_AB, 0, lv.PART_INDICATOR | lv.STATE_PRESSED )


lv.obj_set_style_radius(ui_Slider_AB,  12, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Slider_AB,  0, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Slider_AB,  255, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Slider_AB,  ui_img_pot_hor_knob_png, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_color(ui_Slider_AB,  lv.color_hex(0x000000), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_opa(ui_Slider_AB, 100, lv.PART_KNOB| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_width(ui_Slider_AB,  30, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_spread(ui_Slider_AB,  0, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_ofs_x(ui_Slider_AB,  5, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_ofs_y(ui_Slider_AB,  5, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Slider_AB,  -1, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Slider_AB,  -1, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Slider_AB,  -5, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Slider_AB,  -4, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_color(ui_Slider_AB,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_bg_opa(ui_Slider_AB, 255, lv.PART_KNOB| lv.STATE_PRESSED )
lv.obj_set_style_shadow_color(ui_Slider_AB,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_opa(ui_Slider_AB, 255, lv.PART_KNOB| lv.STATE_PRESSED )
lv.obj_set_style_shadow_width(ui_Slider_AB,  40, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_spread(ui_Slider_AB,  0, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_ofs_x(ui_Slider_AB,  0, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_ofs_y(ui_Slider_AB,  0, lv.PART_KNOB | lv.STATE_PRESSED )

ui_A = lv.label_create(ui_Footer)
lv.label_set_text(ui_A, "A")
lv.obj_set_width(ui_A, 18)
lv.obj_set_height(ui_A, 24)
lv.obj_set_x(ui_A, 40)
lv.obj_set_y(ui_A, 0)
lv.obj_set_align(ui_A,  lv.ALIGN_LEFT_MID)
lv.obj_set_style_text_color(ui_A,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_A, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_A,  lv.font_montserrat_26, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_B = lv.label_create(ui_Footer)
lv.label_set_text(ui_B, "B\n")
lv.obj_set_width(ui_B, 18)
lv.obj_set_height(ui_B, 24)
lv.obj_set_x(ui_B, -40)
lv.obj_set_y(ui_B, 0)
lv.obj_set_align(ui_B,  lv.ALIGN_RIGHT_MID)
lv.obj_set_style_text_color(ui_B,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_B, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_B,  lv.font_montserrat_26, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Background = lv.obj_create(ui_Audio_Player)
lv.obj_set_width(ui_Background, lv.pct(100))
lv.obj_set_height(ui_Background, lv.pct(88))
lv.obj_set_x(ui_Background, 0)
lv.obj_set_y(ui_Background, -28)
lv.obj_set_align(ui_Background,  lv.ALIGN_TOP_MID)
lv.obj_clear_flag(ui_Background, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Background,  lv.color_hex(0x4C4E5B), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Background, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_color(ui_Background, lv.color_hex(0x393B46), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Background,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Background,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_dir(ui_Background, lv.GRAD_DIR_VER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Background,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_color(ui_Background,  lv.color_hex(0x191B20), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_opa(ui_Background, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_width(ui_Background,  140, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_spread(ui_Background,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_ofs_x(ui_Background,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_ofs_y(ui_Background,  4, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Content_group = lv.obj_create(ui_Background)
lv.obj_set_width(ui_Content_group, lv.pct(100))
lv.obj_set_height(ui_Content_group, lv.pct(98))
lv.obj_set_x(ui_Content_group, 0)
lv.obj_set_y(ui_Content_group, 20)
lv.obj_set_align(ui_Content_group,  lv.ALIGN_TOP_MID)
lv.obj_clear_flag(ui_Content_group, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Content_group,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Content_group, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Content_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Content_group,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Content_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Content_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Content_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Content_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Content_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Display = lv.obj_create(ui_Content_group)
lv.obj_set_width(ui_Display, lv.pct(95))
lv.obj_set_height(ui_Display, lv.pct(20))
lv.obj_set_x(ui_Display, 0)
lv.obj_set_y(ui_Display, 15)
lv.obj_set_align(ui_Display,  lv.ALIGN_TOP_MID)
lv.obj_clear_flag(ui_Display, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Display,  lv.color_hex(0x272A33), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Display, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Display,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Display,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Display,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_color(ui_Display,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Display, 255, lv.PART_MAIN| lv.STATE_DEFAULT )

ui_Label_artist = lv.label_create(ui_Display)
lv.label_set_long_mode(ui_Label_artist, lv.LABEL_LONG_DOT)
lv.label_set_text(ui_Label_artist, "The Roboto Tech Band")
lv.obj_set_width(ui_Label_artist, 151)
lv.obj_set_height(ui_Label_artist, 17)
# lv.obj_set_style_text_font(ui_Label_artist,  font_mos_semibold_16, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Label_song = lv.label_create(ui_Display)
lv.label_set_long_mode(ui_Label_song, lv.LABEL_LONG_DOT)
lv.label_set_text(ui_Label_song, "Hard Techno")
lv.obj_set_width(ui_Label_song, 152)
lv.obj_set_height(ui_Label_song, 20)
lv.obj_set_x(ui_Label_song, 0)
lv.obj_set_y(ui_Label_song, 22)
lv.obj_set_style_text_color(ui_Label_song,  lv.color_hex(0x7D7F8B), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Label_song, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Label_song,  lv.font_montserrat_16, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Audio_Wave = lv.slider_create(ui_Display)
lv.obj_set_width(ui_Audio_Wave, 289)
lv.obj_set_height(ui_Audio_Wave, 38)
lv.obj_set_align(ui_Audio_Wave,  lv.ALIGN_BOTTOM_LEFT)
lv.slider_set_value(ui_Audio_Wave, 50, lv.ANIM_OFF)  # need refresh: 0,100

if 'NORMAL' == 'RANGE':
    lv.slider_set_left_value(ui_Audio_Wave, 0, lv.ANIM_OFF)


lv.obj_set_style_bg_color(ui_Audio_Wave,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Audio_Wave, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Audio_Wave,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Audio_Wave,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Audio_Wave,  ui_img_audio_wave_1_png, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_opa(ui_Audio_Wave,  50, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Audio_Wave,  lv.color_hex(0xFFFFFF), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Audio_Wave, 0, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Audio_Wave,  0, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Audio_Wave,  255, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Audio_Wave,  ui_img_audio_wave_1_png, lv.PART_INDICATOR | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Audio_Wave,  lv.color_hex(0xFFFFFF), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Audio_Wave, 0, lv.PART_KNOB| lv.STATE_DEFAULT )

ui_Label_Time = lv.label_create(ui_Display)
lv.label_set_text(ui_Label_Time, "04:52")
lv.obj_set_width(ui_Label_Time, 123)
lv.obj_set_height(ui_Label_Time, 39)
lv.obj_set_x(ui_Label_Time, 175)
lv.obj_set_y(ui_Label_Time, -1)
# lv.obj_set_style_text_font(ui_Label_Time,  font_number, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_BTN_EQ = lv.imgbtn_create(ui_Display)
lv.imgbtn_set_src(ui_BTN_EQ, lv.IMGBTN_STATE_RELEASED, None, ui_img_btn_eq_inact_png , None )
lv.imgbtn_set_src(ui_BTN_EQ, lv.IMGBTN_STATE_PRESSED, None, ui_img_btn_eq_act_png, None )
lv.imgbtn_set_src(ui_BTN_EQ, lv.IMGBTN_STATE_DISABLED, None, ui_img_btn_eq_inact_png, None )
lv.imgbtn_set_src(ui_BTN_EQ, lv.IMGBTN_STATE_CHECKED_RELEASED, None, ui_img_btn_eq_act_png, None )
lv.imgbtn_set_src(ui_BTN_EQ, lv.IMGBTN_STATE_CHECKED_PRESSED, None, ui_img_btn_eq_act_png, None )
lv.imgbtn_set_src(ui_BTN_EQ, lv.IMGBTN_STATE_CHECKED_DISABLED, None, ui_img_btn_eq_inact_png, None )
lv.obj_set_width(ui_BTN_EQ, 105)
lv.obj_set_height(ui_BTN_EQ, 105)
lv.obj_set_x(ui_BTN_EQ, 8)
lv.obj_set_y(ui_BTN_EQ, 4)
lv.obj_set_align(ui_BTN_EQ,  lv.ALIGN_BOTTOM_RIGHT)
lv.obj_add_flag(ui_BTN_EQ, lv.OBJ_FLAG_CHECKABLE)

lv.obj_add_event(ui_BTN_EQ, BTN_EQ_eventhandler, lv.EVENT_VALUE_CHANGED, None)
ui_Left_group = lv.obj_create(ui_Content_group)
lv.obj_set_width(ui_Left_group, lv.pct(28))
lv.obj_set_height(ui_Left_group, lv.pct(76))
lv.obj_set_align(ui_Left_group,  lv.ALIGN_BOTTOM_LEFT)
lv.obj_clear_flag(ui_Left_group, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Left_group,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Left_group, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Left_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Left_group,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Left_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Left_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Left_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Left_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Left_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Slider_group_left = lv.obj_create(ui_Left_group)
lv.obj_set_height(ui_Slider_group_left, 369)
lv.obj_set_width(ui_Slider_group_left, lv.pct(100))
lv.obj_set_x(ui_Slider_group_left, 0)
lv.obj_set_y(ui_Slider_group_left, 20)
lv.obj_set_align(ui_Slider_group_left,  lv.ALIGN_TOP_MID)
lv.obj_clear_flag(ui_Slider_group_left, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Slider_group_left,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider_group_left, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Slider_group_left,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Slider_group_left,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Slider_group_left,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Max = lv.label_create(ui_Slider_group_left)
lv.label_set_text(ui_Max, "MAX")
lv.obj_set_width(ui_Max, 38)
lv.obj_set_height(ui_Max, 19)
lv.obj_set_x(ui_Max, 0)
lv.obj_set_y(ui_Max, -20)
lv.obj_set_align(ui_Max,  lv.ALIGN_TOP_MID)
lv.obj_set_style_text_color(ui_Max,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Max, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Max,  lv.TEXT_ALIGN_CENTER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Max,  lv.font_montserrat_16, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Min = lv.label_create(ui_Slider_group_left)
lv.label_set_text(ui_Min, "MIN")
lv.obj_set_width(ui_Min, 35)
lv.obj_set_height(ui_Min, 19)
lv.obj_set_x(ui_Min, 0)
lv.obj_set_y(ui_Min, 20)
lv.obj_set_align(ui_Min,  lv.ALIGN_BOTTOM_MID)
lv.obj_set_style_text_color(ui_Min,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Min, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Min,  lv.TEXT_ALIGN_CENTER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Min,  lv.font_montserrat_16, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Slider2 = lv.slider_create(ui_Slider_group_left)
lv.obj_set_width(ui_Slider2, 65)
lv.obj_set_height(ui_Slider2, 289)
lv.obj_set_align(ui_Slider2,  lv.ALIGN_CENTER)
lv.slider_set_value(ui_Slider2, 30, lv.ANIM_OFF)  # need refresh: 0,100


lv.obj_set_style_bg_color(ui_Slider2,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider2, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Slider2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Slider2,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Slider2,  ui_img_pot_ver_line_png, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Slider2,  28, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Slider2,  28, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Slider2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Slider2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Slider2,  lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider2, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Slider2,  0, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Slider2,  255, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_color(ui_Slider2,  lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_opa(ui_Slider2, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_width(ui_Slider2,  50, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_spread(ui_Slider2,  0, lv.PART_INDICATOR | lv.STATE_DEFAULT )

lv.obj_set_style_radius(ui_Slider2,  12, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_color(ui_Slider2,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider2, 0, lv.PART_KNOB| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Slider2,  0, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Slider2,  255, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Slider2,  ui_img_pot_ver_knob_png, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_color(ui_Slider2,  lv.color_hex(0x000000), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_opa(ui_Slider2, 100, lv.PART_KNOB| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_width(ui_Slider2,  30, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_spread(ui_Slider2,  0, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_ofs_x(ui_Slider2,  5, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_ofs_y(ui_Slider2,  5, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Slider2,  3, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Slider2,  2, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Slider2,  6, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Slider2,  6, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_radius(ui_Slider2,  12, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_bg_color(ui_Slider2,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_bg_opa(ui_Slider2, 255, lv.PART_KNOB| lv.STATE_PRESSED )
lv.obj_set_style_shadow_color(ui_Slider2,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_opa(ui_Slider2, 255, lv.PART_KNOB| lv.STATE_PRESSED )
lv.obj_set_style_shadow_width(ui_Slider2,  40, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_spread(ui_Slider2,  0, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_ofs_x(ui_Slider2,  0, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_ofs_y(ui_Slider2,  0, lv.PART_KNOB | lv.STATE_PRESSED )

ui_Cut_1 = lv.obj_create(ui_Left_group)
lv.obj_set_height(ui_Cut_1, 94)
lv.obj_set_width(ui_Cut_1, lv.pct(100))
lv.obj_set_align(ui_Cut_1,  lv.ALIGN_BOTTOM_MID)
lv.obj_clear_flag(ui_Cut_1, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Cut_1,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Cut_1, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Cut_1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Cut_1,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Cut_1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Cut_1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Cut_1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Cut_1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Cut_1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_BTN_Cut_Left = lv.imgbtn_create(ui_Cut_1)
lv.imgbtn_set_src(ui_BTN_Cut_Left, lv.IMGBTN_STATE_RELEASED, None, ui_img_btn_1_inact_png, None )
lv.imgbtn_set_src(ui_BTN_Cut_Left, lv.IMGBTN_STATE_PRESSED, None, ui_img_btn_1_act_png, None )
lv.imgbtn_set_src(ui_BTN_Cut_Left, lv.IMGBTN_STATE_DISABLED, None, ui_img_btn_1_inact_png, None )
lv.imgbtn_set_src(ui_BTN_Cut_Left, lv.IMGBTN_STATE_CHECKED_RELEASED, None, ui_img_btn_1_act_png, None )
lv.imgbtn_set_src(ui_BTN_Cut_Left, lv.IMGBTN_STATE_CHECKED_PRESSED, None, ui_img_btn_1_act_png, None )
lv.imgbtn_set_src(ui_BTN_Cut_Left, lv.IMGBTN_STATE_CHECKED_DISABLED, None, ui_img_btn_1_inact_png, None )
lv.obj_set_width(ui_BTN_Cut_Left, 125)
lv.obj_set_height(ui_BTN_Cut_Left, 94)
lv.obj_set_align(ui_BTN_Cut_Left,  lv.ALIGN_CENTER)
lv.obj_add_flag(ui_BTN_Cut_Left, lv.OBJ_FLAG_CHECKABLE)

ui_Label_Cut_1 = lv.label_create(ui_BTN_Cut_Left)
lv.label_set_text(ui_Label_Cut_1, "CUT")
lv.obj_set_width(ui_Label_Cut_1, 35)
lv.obj_set_height(ui_Label_Cut_1, 19)
lv.obj_set_align(ui_Label_Cut_1,  lv.ALIGN_CENTER)
lv.obj_set_style_text_color(ui_Label_Cut_1,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Label_Cut_1, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Label_Cut_1,  lv.TEXT_ALIGN_AUTO, lv.PART_MAIN | lv.STATE_DEFAULT )
# lv.obj_set_style_text_font(ui_Label_Cut_1,  font_mos_semibold_16, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_add_event(ui_Label_Cut_1, Label_Cut_1_eventhandler, lv.EVENT_CLICKED, None)
ui_Right_group = lv.obj_create(ui_Content_group)
lv.obj_set_width(ui_Right_group, lv.pct(28))
lv.obj_set_height(ui_Right_group, lv.pct(76))
lv.obj_set_align(ui_Right_group,  lv.ALIGN_BOTTOM_RIGHT)
lv.obj_clear_flag(ui_Right_group, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Right_group,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Right_group, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Right_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Right_group,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Right_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Right_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Right_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Right_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Right_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Cut_3 = lv.obj_create(ui_Right_group)
lv.obj_set_height(ui_Cut_3, 94)
lv.obj_set_width(ui_Cut_3, lv.pct(100))
lv.obj_set_align(ui_Cut_3,  lv.ALIGN_BOTTOM_MID)
lv.obj_clear_flag(ui_Cut_3, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Cut_3,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Cut_3, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Cut_3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Cut_3,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Cut_3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Cut_3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Cut_3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Cut_3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Cut_3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_BTN_Cut_Left1 = lv.imgbtn_create(ui_Cut_3)
lv.imgbtn_set_src(ui_BTN_Cut_Left1, lv.IMGBTN_STATE_RELEASED, None, ui_img_btn_1_inact_png, None )
lv.imgbtn_set_src(ui_BTN_Cut_Left1, lv.IMGBTN_STATE_PRESSED, None, ui_img_btn_1_act_png, None )
lv.imgbtn_set_src(ui_BTN_Cut_Left1, lv.IMGBTN_STATE_DISABLED, None, ui_img_btn_1_inact_png, None )
lv.imgbtn_set_src(ui_BTN_Cut_Left1, lv.IMGBTN_STATE_CHECKED_RELEASED, None, ui_img_btn_1_act_png, None )
lv.imgbtn_set_src(ui_BTN_Cut_Left1, lv.IMGBTN_STATE_CHECKED_PRESSED, None, ui_img_btn_1_act_png, None )
lv.imgbtn_set_src(ui_BTN_Cut_Left1, lv.IMGBTN_STATE_CHECKED_DISABLED, None, ui_img_btn_1_inact_png, None )
lv.obj_set_width(ui_BTN_Cut_Left1, 125)
lv.obj_set_height(ui_BTN_Cut_Left1, 94)
lv.obj_set_align(ui_BTN_Cut_Left1,  lv.ALIGN_CENTER)
lv.obj_add_flag(ui_BTN_Cut_Left1, lv.OBJ_FLAG_CHECKABLE)

ui_Label_Cut_3 = lv.label_create(ui_BTN_Cut_Left1)
lv.label_set_text(ui_Label_Cut_3, "CUT")
lv.obj_set_width(ui_Label_Cut_3, 35)
lv.obj_set_height(ui_Label_Cut_3, 19)
lv.obj_set_align(ui_Label_Cut_3,  lv.ALIGN_CENTER)
lv.obj_set_style_text_color(ui_Label_Cut_3,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Label_Cut_3, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Label_Cut_3,  lv.TEXT_ALIGN_AUTO, lv.PART_MAIN | lv.STATE_DEFAULT )
# lv.obj_set_style_text_font(ui_Label_Cut_3,  font_mos_semibold_16, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_add_event(ui_BTN_Cut_Left1, Label_Cut_3_eventhandler, lv.EVENT_CLICKED, None)
ui_Slider_group_right = lv.obj_create(ui_Right_group)
lv.obj_set_height(ui_Slider_group_right, 369)
lv.obj_set_width(ui_Slider_group_right, lv.pct(100))
lv.obj_set_x(ui_Slider_group_right, 0)
lv.obj_set_y(ui_Slider_group_right, 20)
lv.obj_set_align(ui_Slider_group_right,  lv.ALIGN_TOP_MID)
lv.obj_clear_flag(ui_Slider_group_right, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Slider_group_right,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider_group_right, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Slider_group_right,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Slider_group_right,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Slider_group_right,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Max1 = lv.label_create(ui_Slider_group_right)
lv.label_set_text(ui_Max1, "MAX")
lv.obj_set_width(ui_Max1, 38)
lv.obj_set_height(ui_Max1, 19)
lv.obj_set_x(ui_Max1, 0)
lv.obj_set_y(ui_Max1, -20)
lv.obj_set_align(ui_Max1,  lv.ALIGN_TOP_MID)
lv.obj_set_style_text_color(ui_Max1,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Max1, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Max1,  lv.TEXT_ALIGN_CENTER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Max1,  lv.font_montserrat_16, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Min2 = lv.label_create(ui_Slider_group_right)
lv.label_set_text(ui_Min2, "MIN")
lv.obj_set_width(ui_Min2, 35)
lv.obj_set_height(ui_Min2, 19)
lv.obj_set_x(ui_Min2, 0)
lv.obj_set_y(ui_Min2, 20)
lv.obj_set_align(ui_Min2,  lv.ALIGN_BOTTOM_MID)
lv.obj_set_style_text_color(ui_Min2,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Min2, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Min2,  lv.TEXT_ALIGN_CENTER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Min2,  lv.font_montserrat_16, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Slider3 = lv.slider_create(ui_Slider_group_right)
lv.obj_set_width(ui_Slider3, 65)
lv.obj_set_height(ui_Slider3, 289)
lv.obj_set_align(ui_Slider3,  lv.ALIGN_CENTER)
lv.slider_set_value(ui_Slider3, 80, lv.ANIM_OFF)  # need refresh: 0,100

if 'NORMAL' == 'RANGE':
    lv.slider_set_left_value(ui_Slider3, 0, lv.ANIM_OFF)

lv.obj_set_style_bg_color(ui_Slider3,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider3, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Slider3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Slider3,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Slider3,  ui_img_pot_ver_line_png, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Slider3,  28, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Slider3,  28, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Slider3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Slider3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Slider3,  lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider3, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Slider3,  0, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Slider3,  255, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_color(ui_Slider3,  lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_opa(ui_Slider3, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_width(ui_Slider3,  50, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_spread(ui_Slider3,  0, lv.PART_INDICATOR | lv.STATE_DEFAULT )

lv.obj_set_style_radius(ui_Slider3,  12, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_color(ui_Slider3,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider3, 0, lv.PART_KNOB| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Slider3,  0, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Slider3,  255, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Slider3,  ui_img_pot_ver_knob_png, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_color(ui_Slider3,  lv.color_hex(0x000000), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_opa(ui_Slider3, 100, lv.PART_KNOB| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_width(ui_Slider3,  30, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_spread(ui_Slider3,  0, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_ofs_x(ui_Slider3,  5, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_ofs_y(ui_Slider3,  5, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Slider3,  3, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Slider3,  2, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Slider3,  6, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Slider3,  6, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_radius(ui_Slider3,  12, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_bg_color(ui_Slider3,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_bg_opa(ui_Slider3, 255, lv.PART_KNOB| lv.STATE_PRESSED )
lv.obj_set_style_shadow_color(ui_Slider3,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_opa(ui_Slider3, 255, lv.PART_KNOB| lv.STATE_PRESSED )
lv.obj_set_style_shadow_width(ui_Slider3,  40, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_spread(ui_Slider3,  0, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_ofs_x(ui_Slider3,  0, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_ofs_y(ui_Slider3,  0, lv.PART_KNOB | lv.STATE_PRESSED )

ui_Center_group = lv.obj_create(ui_Content_group)
lv.obj_set_width(ui_Center_group, lv.pct(35))
lv.obj_set_height(ui_Center_group, lv.pct(76))
lv.obj_set_align(ui_Center_group,  lv.ALIGN_BOTTOM_MID)
lv.obj_clear_flag(ui_Center_group, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Center_group,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Center_group, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Center_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Center_group,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Center_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Center_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Center_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Center_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Center_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Play = lv.obj_create(ui_Center_group)
lv.obj_set_width(ui_Play, lv.pct(100))
lv.obj_set_height(ui_Play, 2001 | (1 << 29))   # 128
lv.obj_set_align(ui_Play,  lv.ALIGN_BOTTOM_MID)
lv.obj_clear_flag(ui_Play, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Play,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Play, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Play,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Play,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Play,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Play,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Play,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Play,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Play,  0, lv.PART_MAIN | lv.STATE_DEFAULT )


ui_BTN_Play = lv.imgbtn_create(ui_Play)
lv.imgbtn_set_src(ui_BTN_Play, lv.IMGBTN_STATE_RELEASED, None, ui_img_btn_play_inact_png, None )
lv.imgbtn_set_src(ui_BTN_Play, lv.IMGBTN_STATE_PRESSED, None, ui_img_btn_play_act_png, None )
lv.imgbtn_set_src(ui_BTN_Play, lv.IMGBTN_STATE_DISABLED, None, ui_img_btn_play_inact_png, None )
lv.imgbtn_set_src(ui_BTN_Play, lv.IMGBTN_STATE_CHECKED_RELEASED, None, ui_img_btn_play_act_png, None )
lv.imgbtn_set_src(ui_BTN_Play, lv.IMGBTN_STATE_CHECKED_PRESSED, None, ui_img_btn_play_act_png, None )
lv.imgbtn_set_src(ui_BTN_Play, lv.IMGBTN_STATE_CHECKED_DISABLED, None, ui_img_btn_play_inact_png, None )
lv.obj_set_width(ui_BTN_Play, 145)
lv.obj_set_height(ui_BTN_Play, 145)
lv.obj_set_align(ui_BTN_Play,  lv.ALIGN_CENTER)
lv.obj_add_flag(ui_BTN_Play, lv.OBJ_FLAG_CHECKABLE)

ui_Indicator_group = lv.obj_create(ui_Center_group)
lv.obj_set_height(ui_Indicator_group, 369)
lv.obj_set_width(ui_Indicator_group, lv.pct(100))
lv.obj_set_x(ui_Indicator_group, 0)
lv.obj_set_y(ui_Indicator_group, 20)
lv.obj_set_align(ui_Indicator_group,  lv.ALIGN_TOP_MID)
lv.obj_clear_flag(ui_Indicator_group, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Indicator_group,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Indicator_group, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Indicator_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Indicator_group,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Indicator_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Label_Levels = lv.label_create(ui_Indicator_group)
lv.label_set_text(ui_Label_Levels, "LEVEL")
lv.obj_set_width(ui_Label_Levels, 77)
lv.obj_set_height(ui_Label_Levels, 17)
lv.obj_set_x(ui_Label_Levels, 0)
lv.obj_set_y(ui_Label_Levels, -18)
lv.obj_set_align(ui_Label_Levels,  lv.ALIGN_TOP_MID)
lv.obj_set_style_text_color(ui_Label_Levels,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Label_Levels, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Label_Levels,  lv.TEXT_ALIGN_CENTER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Label_Levels,  lv.font_montserrat_16, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Min1 = lv.label_create(ui_Indicator_group)
lv.label_set_text(ui_Min1, "00\n-02\n-04\n-06\n-08\n-10\n-12\n-14\n-18")
lv.obj_set_width(ui_Min1, 24)
lv.obj_set_height(ui_Min1, 293)
lv.obj_set_x(ui_Min1, 0)
lv.obj_set_y(ui_Min1, 24)
lv.obj_set_align(ui_Min1,  lv.ALIGN_TOP_MID)
lv.obj_set_style_text_color(ui_Min1,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Min1, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_letter_space(ui_Min1, 0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_line_space(ui_Min1, 19, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Min1,  lv.TEXT_ALIGN_CENTER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Min1,  lv.font_montserrat_12, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Indicator_Left = lv.slider_create(ui_Indicator_group)
lv.obj_set_width(ui_Indicator_Left, 33)
lv.obj_set_height(ui_Indicator_Left, 289)
lv.obj_set_align(ui_Indicator_Left,  lv.ALIGN_LEFT_MID)

if 0 < 29: 
    lv.slider_set_range(ui_Indicator_Left, 0,29)
    
    
lv.slider_set_value(ui_Indicator_Left, 10, lv.ANIM_OFF)  # need refresh: 0,29

if 'NORMAL' == 'RANGE':
    lv.slider_set_left_value(ui_Indicator_Left, 0, lv.ANIM_OFF)
                                     
lv.obj_set_style_radius(ui_Indicator_Left,  4, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_color(ui_Indicator_Left,  lv.color_hex(0x272A33), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Indicator_Left, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Indicator_Left,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Indicator_Left,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Indicator_Left,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Indicator_Left,  2, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Indicator_Left,  2, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Indicator_Left,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Indicator_Left,  0, lv.PART_MAIN | lv.STATE_DEFAULT )


lv.obj_set_style_radius(ui_Indicator_Left,  4, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_color(ui_Indicator_Left,  lv.color_hex(0xFFFFFF), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Indicator_Left, 0, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Indicator_Left,  0, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Indicator_Left,  255, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Indicator_Left,  ui_img_indicator_ver_png, lv.PART_INDICATOR | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Indicator_Left,  lv.color_hex(0xFFFFFF), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Indicator_Left, 0, lv.PART_KNOB| lv.STATE_DEFAULT )

ui_Indicator_Right = lv.slider_create(ui_Indicator_group)
lv.obj_set_width(ui_Indicator_Right, 33)
lv.obj_set_height(ui_Indicator_Right, 289)
lv.obj_set_align(ui_Indicator_Right,  lv.ALIGN_RIGHT_MID)


if 0 < 29: 
    lv.slider_set_range(ui_Indicator_Right, 0,29)
    

lv.slider_set_value(ui_Indicator_Right, 25, lv.ANIM_OFF)  # need refresh: 0,29


if 'NORMAL' == 'RANGE':
    lv.slider_set_left_value(ui_Indicator_Right, 0, lv.ANIM_OFF)
    
    
lv.obj_set_style_radius(ui_Indicator_Right,  4, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_color(ui_Indicator_Right,  lv.color_hex(0x272A33), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Indicator_Right, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Indicator_Right,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Indicator_Right,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Indicator_Right,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Indicator_Right,  2, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Indicator_Right,  2, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Indicator_Right,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Indicator_Right,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_set_style_radius(ui_Indicator_Right,  4, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_color(ui_Indicator_Right,  lv.color_hex(0xFFFFFF), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Indicator_Right, 0, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Indicator_Right,  0, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Indicator_Right,  255, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Indicator_Right,  ui_img_indicator_ver_png, lv.PART_INDICATOR | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Indicator_Right,  lv.color_hex(0xFFFFFF), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Indicator_Right, 0, lv.PART_KNOB| lv.STATE_DEFAULT )

ui_EQ_group = lv.obj_create(ui_Content_group)
lv.obj_set_height(ui_EQ_group, 164)
lv.obj_set_width(ui_EQ_group, lv.pct(95))
lv.obj_set_x(ui_EQ_group, 0)
lv.obj_set_y(ui_EQ_group, -70)
lv.obj_set_align(ui_EQ_group,  lv.ALIGN_CENTER)
lv.obj_add_flag(ui_EQ_group, lv.OBJ_FLAG_HIDDEN)
lv.obj_clear_flag(ui_EQ_group, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_EQ_group,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_EQ_group, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_border_color(ui_EQ_group,  lv.color_hex(0x747682), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_opa(ui_EQ_group, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_EQ_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_EQ_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_EQ_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_EQ_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_EQ1 = lv.obj_create(ui_EQ_group)
lv.obj_set_height(ui_EQ1, 164)
lv.obj_set_width(ui_EQ1, lv.pct(33))
lv.obj_set_align(ui_EQ1,  lv.ALIGN_LEFT_MID)
lv.obj_set_style_bg_color(ui_EQ1,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_EQ1, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_EQ1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_EQ1,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_EQ1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Image2 = lv.img_create(ui_EQ1)
lv.img_set_src(ui_Image2, ui_img_btn_knob_png)
lv.obj_set_width(ui_Image2, 104)
lv.obj_set_height(ui_Image2, 105)
lv.obj_set_x(ui_Image2, 0)
lv.obj_set_y(ui_Image2, -12)
lv.obj_set_align(ui_Image2,  lv.ALIGN_CENTER)
lv.obj_add_flag(ui_Image2, lv.OBJ_FLAG_ADV_HITTEST)

ui_Arc1 = lv.arc_create(ui_EQ1)
lv.obj_set_width(ui_Arc1, 95)
lv.obj_set_height(ui_Arc1, 97)
lv.obj_set_x(ui_Arc1, 0)
lv.obj_set_y(ui_Arc1, -12)
lv.obj_set_align(ui_Arc1,  lv.ALIGN_CENTER)
lv.arc_set_range(ui_Arc1, 10, 1000)
lv.arc_set_value(ui_Arc1, 50)
lv.arc_set_bg_angles(ui_Arc1, 129,51)
lv.obj_set_style_pad_left(ui_Arc1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Arc1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Arc1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Arc1,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_arc_color(ui_Arc1, lv.color_hex(0x4040FF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_arc_opa(ui_Arc1, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_arc_width(ui_Arc1, 20, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_set_style_arc_color(ui_Arc1, lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_arc_opa(ui_Arc1, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_arc_width(ui_Arc1, 2, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_arc_rounded(ui_Arc1, True, lv.PART_INDICATOR | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Arc1,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Arc1, 0, lv.PART_KNOB| lv.STATE_DEFAULT )

ui_Label_Low = lv.label_create(ui_EQ1)
lv.label_set_text(ui_Label_Low, "LOW")
lv.obj_set_width(ui_Label_Low, 68)
lv.obj_set_height(ui_Label_Low, 17)
lv.obj_set_align(ui_Label_Low,  lv.ALIGN_BOTTOM_MID)
lv.obj_set_style_text_color(ui_Label_Low,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Label_Low, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Label_Low,  lv.TEXT_ALIGN_CENTER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Label_Low,  lv.font_montserrat_16, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_EQ2 = lv.obj_create(ui_EQ_group)
lv.obj_set_height(ui_EQ2, 164)
lv.obj_set_width(ui_EQ2, lv.pct(33))
lv.obj_set_align(ui_EQ2,  lv.ALIGN_CENTER)
lv.obj_set_style_bg_color(ui_EQ2,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_EQ2, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_EQ2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_EQ2,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_EQ2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Image3 = lv.img_create(ui_EQ2)
lv.img_set_src(ui_Image3, ui_img_btn_knob_png)
lv.obj_set_width(ui_Image3, 104)
lv.obj_set_height(ui_Image3, 105)
lv.obj_set_x(ui_Image3, 0)
lv.obj_set_y(ui_Image3, -12)
lv.obj_set_align(ui_Image3,  lv.ALIGN_CENTER)
lv.obj_add_flag(ui_Image3, lv.OBJ_FLAG_ADV_HITTEST)

ui_Arc2 = lv.arc_create(ui_EQ2)
lv.obj_set_width(ui_Arc2, 95)
lv.obj_set_height(ui_Arc2, 97)
lv.obj_set_x(ui_Arc2, 0)
lv.obj_set_y(ui_Arc2, -12)
lv.obj_set_align(ui_Arc2,  lv.ALIGN_CENTER)
lv.arc_set_range(ui_Arc2, 10,1000)
lv.arc_set_value(ui_Arc2, 600)
lv.arc_set_bg_angles(ui_Arc2, 129,51)
lv.obj_set_style_pad_left(ui_Arc2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Arc2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Arc2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Arc2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_arc_color(ui_Arc2,  lv.color_hex(0x4040FF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_arc_opa(ui_Arc2, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_arc_width(ui_Arc2,  20, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_set_style_arc_color(ui_Arc2,  lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_arc_opa(ui_Arc2, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_arc_width(ui_Arc2,  2, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_arc_rounded(ui_Arc2,  True, lv.PART_INDICATOR | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Arc2,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Arc2, 0, lv.PART_KNOB| lv.STATE_DEFAULT )

ui_Label_Mid = lv.label_create(ui_EQ2)
lv.label_set_text(ui_Label_Mid, "MID")
lv.obj_set_width(ui_Label_Mid, 68)
lv.obj_set_height(ui_Label_Mid, 17)
lv.obj_set_align(ui_Label_Mid,  lv.ALIGN_BOTTOM_MID)
lv.obj_set_style_text_color(ui_Label_Mid,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Label_Mid, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Label_Mid,  lv.TEXT_ALIGN_CENTER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Label_Mid,  lv.font_montserrat_16, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_EQ3 = lv.obj_create(ui_EQ_group)
lv.obj_set_height(ui_EQ3, 164)
lv.obj_set_width(ui_EQ3, lv.pct(33))
lv.obj_set_align(ui_EQ3,  lv.ALIGN_RIGHT_MID)
lv.obj_set_style_bg_color(ui_EQ3,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_EQ3, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_EQ3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_EQ3,  255, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_EQ3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Image4 = lv.img_create(ui_EQ3)
lv.img_set_src(ui_Image4, ui_img_btn_knob_png)
lv.obj_set_width(ui_Image4, 104)
lv.obj_set_height(ui_Image4, 105)
lv.obj_set_x(ui_Image4, 0)
lv.obj_set_y(ui_Image4, -12)
lv.obj_set_align(ui_Image4,  lv.ALIGN_CENTER)
lv.obj_add_flag(ui_Image4, lv.OBJ_FLAG_ADV_HITTEST)

ui_Arc3 = lv.arc_create(ui_EQ3)
lv.obj_set_width(ui_Arc3, 95)
lv.obj_set_height(ui_Arc3, 97)
lv.obj_set_x(ui_Arc3, 0)
lv.obj_set_y(ui_Arc3, -12)
lv.obj_set_align(ui_Arc3,  lv.ALIGN_CENTER)
lv.arc_set_range(ui_Arc3, 10,1000)
lv.arc_set_value(ui_Arc3, 900)
lv.arc_set_bg_angles(ui_Arc3, 129,51)
lv.obj_set_style_pad_left(ui_Arc3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Arc3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Arc3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Arc3,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_arc_color(ui_Arc3,  lv.color_hex(0x4040FF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_arc_opa(ui_Arc3, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_arc_width(ui_Arc3,  20, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_set_style_arc_color(ui_Arc3,  lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_arc_opa(ui_Arc3, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_arc_width(ui_Arc3,  2, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_arc_rounded(ui_Arc3,  True, lv.PART_INDICATOR | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Arc3,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Arc3, 0, lv.PART_KNOB| lv.STATE_DEFAULT )

ui_Label_High = lv.label_create(ui_EQ3)
lv.label_set_text(ui_Label_High, "HIGH")
lv.obj_set_width(ui_Label_High, 68)
lv.obj_set_height(ui_Label_High, 17)
lv.obj_set_align(ui_Label_High,  lv.ALIGN_BOTTOM_MID)
lv.obj_set_style_text_color(ui_Label_High,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Label_High, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Label_High,  lv.TEXT_ALIGN_CENTER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Label_High,  lv.font_montserrat_16, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Tempo_group = lv.obj_create(ui_Content_group)
lv.obj_set_height(ui_Tempo_group, 164)
lv.obj_set_width(ui_Tempo_group, lv.pct(95))
lv.obj_set_x(ui_Tempo_group, 0)
lv.obj_set_y(ui_Tempo_group, -140)
lv.obj_set_align(ui_Tempo_group,  lv.ALIGN_BOTTOM_MID)
lv.obj_add_flag(ui_Tempo_group, lv.OBJ_FLAG_HIDDEN)
lv.obj_clear_flag(ui_Tempo_group, lv.OBJ_FLAG_SCROLLABLE)
lv.obj_set_style_bg_color(ui_Tempo_group,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Tempo_group, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_border_width(ui_Tempo_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Tempo_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Tempo_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Tempo_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Tempo_group,  0, lv.PART_MAIN | lv.STATE_DEFAULT )

ui_Slider_AB_2 = lv.slider_create(ui_Tempo_group)
lv.obj_set_width(ui_Slider_AB_2, 315)
lv.obj_set_height(ui_Slider_AB_2, 79)
lv.obj_set_x(ui_Slider_AB_2, 0)
lv.obj_set_y(ui_Slider_AB_2, -12)
lv.obj_set_align(ui_Slider_AB_2,  lv.ALIGN_CENTER)
lv.slider_set_mode(ui_Slider_AB_2, lv.SLIDER_MODE_SYMMETRICAL)


if -100 < 100:
    lv.slider_set_range(ui_Slider_AB_2, -100,100)


lv.slider_set_value(ui_Slider_AB_2, 100, lv.ANIM_OFF)  # need refresh: -100,100


if 'SYMMETRICAL' == 'RANGE':
    lv.slider_set_left_value(ui_Slider_AB_2, 0, lv.ANIM_OFF)


lv.obj_set_style_bg_color(ui_Slider_AB_2,  lv.color_hex(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider_AB_2, 0, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Slider_AB_2,  ui_img_pot_hor_line_tempo_png, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Slider_AB_2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Slider_AB_2,  0, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Slider_AB_2,  35, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Slider_AB_2,  35, lv.PART_MAIN | lv.STATE_DEFAULT )

lv.obj_set_style_bg_color(ui_Slider_AB_2,  lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider_AB_2, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_color(ui_Slider_AB_2,  lv.color_hex(0x50FF7D), lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_opa(ui_Slider_AB_2, 255, lv.PART_INDICATOR| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_width(ui_Slider_AB_2,  50, lv.PART_INDICATOR | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_spread(ui_Slider_AB_2,  0, lv.PART_INDICATOR | lv.STATE_DEFAULT )

lv.obj_set_style_radius(ui_Slider_AB_2,  12, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_color(ui_Slider_AB_2,  lv.color_hex(0xFFFFFF), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_opa(ui_Slider_AB_2, 0, lv.PART_KNOB| lv.STATE_DEFAULT )
lv.obj_set_style_bg_main_stop(ui_Slider_AB_2,  0, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_grad_stop(ui_Slider_AB_2,  255, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_bg_img_src(ui_Slider_AB_2,  ui_img_pot_hor_knob_png, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_color(ui_Slider_AB_2,  lv.color_hex(0x000000), lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_opa(ui_Slider_AB_2, 100, lv.PART_KNOB| lv.STATE_DEFAULT )
lv.obj_set_style_shadow_width(ui_Slider_AB_2,  30, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_spread(ui_Slider_AB_2,  0, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_ofs_x(ui_Slider_AB_2,  5, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_shadow_ofs_y(ui_Slider_AB_2,  5, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_left(ui_Slider_AB_2,  -1, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_right(ui_Slider_AB_2,  -1, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_top(ui_Slider_AB_2,  -5, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_pad_bottom(ui_Slider_AB_2,  -4, lv.PART_KNOB | lv.STATE_DEFAULT )
lv.obj_set_style_radius(ui_Slider_AB_2,  12, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_bg_color(ui_Slider_AB_2,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_bg_opa(ui_Slider_AB_2, 255, lv.PART_KNOB| lv.STATE_PRESSED )
lv.obj_set_style_shadow_color(ui_Slider_AB_2,  lv.color_hex(0x50FF7D), lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_opa(ui_Slider_AB_2, 255, lv.PART_KNOB| lv.STATE_PRESSED )
lv.obj_set_style_shadow_width(ui_Slider_AB_2,  40, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_spread(ui_Slider_AB_2,  0, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_ofs_x(ui_Slider_AB_2,  0, lv.PART_KNOB | lv.STATE_PRESSED )
lv.obj_set_style_shadow_ofs_y(ui_Slider_AB_2,  0, lv.PART_KNOB | lv.STATE_PRESSED )

ui_Label_Tempo = lv.label_create(ui_Tempo_group)
lv.label_set_text(ui_Label_Tempo, "TEMPO")
lv.obj_set_width(ui_Label_Tempo, 68)
lv.obj_set_height(ui_Label_Tempo, 17)
lv.obj_set_x(ui_Label_Tempo, 0)
lv.obj_set_y(ui_Label_Tempo, -8)
lv.obj_set_align(ui_Label_Tempo,  lv.ALIGN_BOTTOM_MID)
lv.obj_set_style_text_color(ui_Label_Tempo,  lv.color_hex(0x9395A1), lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_opa(ui_Label_Tempo, 255, lv.PART_MAIN| lv.STATE_DEFAULT )
lv.obj_set_style_text_align(ui_Label_Tempo,  lv.TEXT_ALIGN_CENTER, lv.PART_MAIN | lv.STATE_DEFAULT )
lv.obj_set_style_text_font(ui_Label_Tempo,  lv.font_montserrat_16, lv.PART_MAIN | lv.STATE_DEFAULT )

start = time.time()

while True:
    time.sleep(0.001)
    stop = time.time()
    diff = int((stop * 1000) - (start * 1000))
    start = stop
    lv.tick_inc(diff)
    lv.task_handler()
